-- LOWER / INITCAP / UPPER
SELECT LAST_NAME, LOWER(LAST_NAME), INITCAP(LAST_NAME), UPPER(LAST_NAME)
FROM EMPLOYEES;

--LENGTH / INSTR
SELECT FIRST_NAME, LENGTH(FIRST_NAME), INSTR(FIRST_NAME, 'a')
FROM EMPLOYEES;

--SUBSTR / CONCAT
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 1, 3), CONCAT(FIRST_NAME, LAST_NAME)
FROM EMPLOYEES;

--LPAD / RPAD
SELECT
    RPAD(FIRST_NAME, 10, '-') AS NAME,
    LPAD(SALARY, 10, '*') AS SAL
    FROM EMPLOYEES;
    
--LTRIM / TRIM / RTRIM
SELECT LTRIM('JAVASPECIALIST', 'JAVA')
FROM DUAL;

SELECT TRIM(' JAVASPECIALIST ')
FROM DUAL;

SELECT LTRIM(' JAVASPECIALIST')
FROM DUAL;

SELECT RTRIM('JAVASPECIALIST', 'LIST')
FROM DUAL;


