--데이터의 정렬
--질의에 의해 검색되는 행을 정렬할 수 있습니다.
--ODER BY 절은 SELECT 문장의 가장 뒤에 옵니다.
--ASC : 오름차순으로 정렬합니다. (기본값)
--DESC : 내림차순으로 정렬합니다.
SELECT FIRST_NAME, HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE;

--ORDER BY절에 열 별칭을 사용할 수 있습니다. (WHERE 사용불가)
SELECT FIRST_NAME, SALARY*12 AS ANNSAL
FROM EMPLOYEES
ORDER BY ANNSAL;

SELECT * FROM EMPLOYEES ORDER BY SALARY; -- ASC가 DEFAULT
SELECT * FROM EMPLOYEES ORDER BY SALARY DESC;
SELECT * FROM EMPLOYEES ORDER BY DEPARTMENT_ID, SALARY DESC; -- 부서 아이디로 정렬, 동순위에 대해서 SALARY로 내림차순 정렬

SELECT FIRST_NAME, SALARY*12 AS 연봉 FROM EMPLOYEES ORDER BY 연봉 DESC; -- 엘리어스를 정렬해서 사용할 수 있음.

